#

In [4]:
import pandas as pd

In [1]:
# data frame
data = {
    '이름': ['홍길동', '임꺽정', '이순신'],
    '나이': [30, 35, 40],
    '도시': ['서울', '부산', '광주']
}

df = pd.DataFrame(data)
print(df)

    이름  나이  도시
0  홍길동  30  서울
1  임꺽정  35  부산
2  이순신  40  광주

In [5]:
# vector 연산 지원, 속도가 빠름

names = pd.Series(['김나나', '이매진', '타블로'])
names

0    김나나
1    이매진
2    타블로
dtype: object

In [12]:
# df = pd.read_excel('example.xlsx')
test = pd.read_csv('/content/sample_data/california_housing_test.csv')

## head()
* DataFrame 위 처음 몇 줄(기본적으로 5줄)을 보여줌
* 빨리 점검 가능

In [13]:
print(test.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0
1    -118.30     34.26                43.0       1510.0           310.0
2    -117.81     33.78                27.0       3589.0           507.0
3    -118.36     33.82                28.0         67.0            15.0
4    -119.67     36.33                19.0       1241.0           244.0

   population  households  median_income  median_house_value
0      1537.0       606.0         6.6085            344700.0
1       809.0       277.0         3.5990            176500.0
2      1484.0       495.0         5.7934            270500.0
3        49.0        11.0         6.1359            330000.0
4       850.0       237.0         2.9375             81700.0

In [14]:
print(test.tail())

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

## info()

In [17]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB
None

In [16]:
test2 = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [18]:
print(test2.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0

   population  households  median_income  median_house_value
0      1015.0       472.0         1.4936             66900.0
1      1129.0       463.0         1.8200             80100.0
2       333.0       117.0         1.6509             85700.0
3       515.0       226.0         3.1917             73400.0
4       624.0       262.0         1.9250             65500.0

## Null
* Null 있으면 안됨. 대부분의 machine learning, deep learning 처리 안됨.
* Null 을 임의로 '0', 'nan' 으로 치환하면 난감한 상황에 빠질 수 있음

## describe()

* check min, max first (이상문자가 들어가기도 함)
* mean check
* 25%, 50% 75% check (편중되어 있는지, 잘 분포되어 있는지)
  ex) 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 6,.. (우리 어플 사용량)

In [19]:
test2.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

## inplace() = True

## dropna()
엑셀의 헤더나 pivot table 의 헤더와 비슷

In [ ]:
# inplace 매개변수를 사용하지 않는 경우
df = df.dropna()

# inplace 사용하는 경우

## 결측치 처리
1. info(), describe() 로 확인
2. 문자형 데이터는 describe 로도 통계량이 나오지 않음. 평균등 계산 안되니까.
3. dropna(inplace=False)  --> 결측치 제거
4. 원본으로 작업하지 말고, 복사본으로 처리

In [20]:
import pandas as pd
import numpy as np

# 샘플 데이터프레임 생성
data = {'이름': ['홍길동', '임꺽정', None],
        '나이': [30, None, 40],
        '도시': ['서울', '부산', '광주']}
df = pd.DataFrame(data)

# 결측치가 포함된 데이터프레임 출력
print("원본 데이터프레임:\n", df)

# 결측치 제거
df.dropna(inplace=True)

# 결측치가 제거된 데이터프레임 출력
print("\n결측치 제거 후 데이터프레임:\n", df)

원본 데이터프레임:
      이름    나이  도시
0   홍길동  30.0  서울
1   임꺽정   NaN  부산
2  None  40.0  광주

결측치 제거 후 데이터프레임:
     이름    나이  도시
0  홍길동  30.0  서울

## DataFrame, Series

In [21]:
# Pandas DataFrame 예시
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Paris', 'Berlin']
})

# 각 속성 호출
print("Shape:", df.shape)
print("Data Types:\n", df.dtypes)
print("Index:", df.index)
print("Columns:", df.columns)

Shape: (3, 3)
Data Types:
 Name    object
Age      int64
City    object
dtype: object
Index: RangeIndex(start=0, stop=3, step=1)
Columns: Index(['Name', 'Age', 'City'], dtype='object')

## astype(): 데이터 타입 변환

* 데이터 저장할때 데이터타입을 문자형으로 저장하면 저장용량 더 효율적. ㄱ

In [22]:
import pandas as pd

# 예시 데이터프레임 생성
data = {
    'Name': ['Alice', 'Bob'],  # 문자열 타입
    'Age': ['25', '30'],       # 숫자 데이터를 문자열로 표현
    'Member': ['True', 'False'],  # 불린 데이터를 문자열로 표현
    'Join Date': ['2021-01-01', '2021-07-01']  # 날짜 데이터를 문자열로 표현
}

df = pd.DataFrame(data)

# 데이터 타입 변환
df['Age'] = df['Age'].astype(int)  # 'Age' 열을 정수형으로 변환
df['Member'] = df['Member'].astype(bool)  # 'Member' 열을 불린형으로 변환
df['Join Date'] = pd.to_datetime(df['Join Date'])  # 'Join Date' 열을 datetime으로 변환

# 결과 출력
print(df)
print(df.dtypes)

    Name  Age  Member  Join Date
0  Alice   25    True 2021-01-01
1    Bob   30    True 2021-07-01
Name                 object
Age                   int64
Member                 bool
Join Date    datetime64[ns]
dtype: object

## DataFrame 에서 선택: df['column_name']  ==> Series
* 두개 이상 가져오면 data frame 이 됨

In [2]:
import pandas as pd
import numpy as np

In [3]:
# 예시 데이터프레임 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Paris', 'Berlin']
}
df = pd.DataFrame(data)

# 단일 열 선택 -> 결과는 Series
age_series = df['Age']
print(type(age_series))

# 다중 열 선택 -> 결과는 DataFrame
subset_df = df[['Name', 'City']]
print(type(subset_df))

# loc 사용 예시
print(df.loc[:, 'Age'])

# iloc 사용 예시
print(df.iloc[:, 1])

# 결측치 추가
df.loc[1, 'Age'] = np.nan

# 결측치 확인
print(df['Age'].isnull())

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
0    25
1    30
2    35
Name: Age, dtype: int64
0    25
1    30
2    35
Name: Age, dtype: int64
0    False
1     True
2    False
Name: Age, dtype: bool

In [7]:
test3 = df['Age']
test3

0    25.0
1     NaN
2    35.0
Name: Age, dtype: float64

In [10]:
test3 = df[['Name', 'City']]
test3

      Name      City
0    Alice  New York
1      Bob     Paris
2  Charlie    Berlin

## Series() 활용

In [11]:
data = pd.Series([10, 20, 30])

In [12]:
data.sum()

60

In [13]:
data.mean()

20.0

In [15]:
data.value_counts()

10    1
20    1
30    1
dtype: int64

In [16]:
import pandas as pd

# Series 생성
data = pd.Series([10, 15, 20, 25, 30])

# 다양한 메서드 활용
print("Minimum:", data.min())          # 최소값
print("Maximum:", data.max())          # 최대값
print("Standard Deviation:", data.std())  # 표준편차
print("Variance:", data.var())          # 분산
print("Number of Unique Values:", data.nunique())  # 고유값 개수

# 데이터프레임 요약
df = pd.DataFrame({
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 55000, 60000, 65000, 70000]
})
print("\nDataFrame Summary:\n", df.describe())
print("\nDataFrame Info:")
df.info()

Minimum: 10
Maximum: 30
Standard Deviation: 7.905694150420948
Variance: 62.5
Number of Unique Values: 5

DataFrame Summary:
              Age       Salary
count   5.000000      5.00000
mean   35.000000  60000.00000
std     7.905694   7905.69415
min    25.000000  50000.00000
25%    30.000000  55000.00000
50%    35.000000  60000.00000
75%    40.000000  65000.00000
max    45.000000  70000.00000

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     5 non-null      int64
 1   Salary  5 non-null      int64
dtypes: int64(2)
memory usage: 208.0 bytes

In [18]:
# 실습!
test = pd.read_csv("/content/sample_data/california_housing_train.csv")
test
# 데이터프레임의 'housing_median_age' 열을 Series로 변환하고 숫자형으로 변환
test_series = test['housing_median_age']
high_age = test_series > 17.0
print("High age:\n", high_age.head())

High age:
 0    False
1     True
2    False
3    False
4     True
Name: housing_median_age, dtype: bool

# Big data 실습

In [2]:
import pandas as pd

dataset = pd.read_csv('/content/The-Big-List-20231127-Reviews-to-4650.csv', encoding='latin1')

In [3]:
dataset.head()

,Review #,Brand,Variety,Style,Country,Stars,T
0,4650,Jasmine,XXL Bihun Segera Penang White Curry,Pack,Malaysia,5,NaN
1,4649,Indomie,Mi Instan Mi Keriting Goreng Spesial,Pack,Indonesia,5,NaN
2,4648,MAMA,Oriental Kitchen Dried Instant Noodles Truffle...,Pack,Thailand,4.5,NaN
3,4647,Ottogi,Jin Jjajang Smoked Black Bean Flavor,Pack,United States,4.5,NaN
4,4646,Samyang Foods,Samyand Ramen,Pack,United States,5,NaN

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4650 entries, 0 to 4649
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  4650 non-null   int64
 1   Brand     4650 non-null   object
 2   Variety   4650 non-null   object
 3   Style     4650 non-null   object
 4   Country   4650 non-null   object
 5   Stars     4648 non-null   object
 6   T         0 non-null      float64
dtypes: float64(1), int64(1), object(5)
memory usage: 254.4+ KB

In [5]:
dataset.describe()

          Review #    T
count  4650.000000  0.0
mean   2325.500000  NaN
std    1342.483706  NaN
min       1.000000  NaN
25%    1163.250000  NaN
50%    2325.500000  NaN
75%    3487.750000  NaN
max    4650.000000  NaN

In [6]:
dataset.value_counts()

Series([], dtype: int64)

In [7]:
dataset['Brand'].value_counts()

Nissin             567
Maruchan           182
Myojo              152
Nongshim           136
Samyang Foods      122
                  ...
Kiseki Foods         1
Xiuhe                1
Dr. McDougall's      1
Hi-Lai Foods         1
Westbrae             1
Name: Brand, Length: 698, dtype: int64

In [8]:
dataset.nunique()

Review #    4650
Brand        698
Variety     4325
Style         10
Country       54
Stars         53
T              0
dtype: int64

In [9]:
# 결측치 제거

dataset.isnull().sum()

Review #       0
Brand          0
Variety        0
Style          0
Country        0
Stars          2
T           4650
dtype: int64

In [10]:
# 결측치 제거

dataset.drop('T', axis=1)

,Review #,Brand,Variety,Style,Country,Stars
0,4650,Jasmine,XXL Bihun Segera Penang White Curry,Pack,Malaysia,5
1,4649,Indomie,Mi Instan Mi Keriting Goreng Spesial,Pack,Indonesia,5
2,4648,MAMA,Oriental Kitchen Dried Instant Noodles Truffle...,Pack,Thailand,4.5
3,4647,Ottogi,Jin Jjajang Smoked Black Bean Flavor,Pack,United States,4.5
4,4646,Samyang Foods,Samyand Ramen,Pack,United States,5
...,...,...,...,...,...,...
4645,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5
4646,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1
4647,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2
4648,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2
4649,1,Westbrae,Miso Ramen,Pack,United States,0.5

In [12]:
dataset.dropna()

Empty DataFrame
Columns: [Review #, Brand, Variety, Style, Country, Stars, T]
Index: []

In [13]:
dataset.head()

,Review #,Brand,Variety,Style,Country,Stars,T
0,4650,Jasmine,XXL Bihun Segera Penang White Curry,Pack,Malaysia,5,NaN
1,4649,Indomie,Mi Instan Mi Keriting Goreng Spesial,Pack,Indonesia,5,NaN
2,4648,MAMA,Oriental Kitchen Dried Instant Noodles Truffle...,Pack,Thailand,4.5,NaN
3,4647,Ottogi,Jin Jjajang Smoked Black Bean Flavor,Pack,United States,4.5,NaN
4,4646,Samyang Foods,Samyand Ramen,Pack,United States,5,NaN

In [14]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4650 entries, 0 to 4649
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  4650 non-null   int64
 1   Brand     4650 non-null   object
 2   Variety   4650 non-null   object
 3   Style     4650 non-null   object
 4   Country   4650 non-null   object
 5   Stars     4648 non-null   object
 6   T         0 non-null      float64
dtypes: float64(1), int64(1), object(5)
memory usage: 254.4+ KB

In [ ]:
# IQR: 75% - 25% 값
# IQR 벗어나는 값: outlier